## Coding Exercise #0701

### 1. TensorFlow basics:

In [ ]:
# Install once.
# !pip install tensorflow
# OR
# !pip install --user tensorflow-gpu

In [ ]:
#Uncomment to force use of CPU.
#import os
#os.environ['CUDA_VISIBLE_DEVICES'] = ''

#Suppress TF warnings
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [1]:
# import tensorflow as tf
import tensorflow as tf
import numpy as np

2024-05-12 10:48:58.575481: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-12 10:48:59.278060: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


#### 1.1. Hello World!

In [2]:
hello = tf.constant("Hello World!")
print(hello.numpy())

b'Hello World!'


2024-05-12 10:51:02.593349: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-12 10:51:02.774759: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-12 10:51:02.774808: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-12 10:51:02.779040: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-05-12 10:51:02.779111: I external/local_xla/xla/stream_executor

#### 1.2. Creating tensors:

In [5]:
hello = tf.constant("Hello World!")                         # String.
const_scalar = tf.constant(7)                               # A scalar tensor.
const_matrix = tf.constant([[1,2], [3,4]])                  # A matrix tensor.
mat_fill = tf.fill((4,4),9)                                 # A 4x4 tensor filled with 9s.
mat_zeros = tf.zeros((3,3))                                 # A 3x3 tensor filled with 0s.
mat_ones = tf.ones((5,5))                                   # A 5x5 tensor filled with 1s.
mat_randn = tf.random.normal((3,3), mean=0, stddev=1.0)     # 3x3 random normal tensor.
mat_randu = tf.random.uniform((4,4), minval=0, maxval=1.0)  # 4x4 random uniform tensor.

In [5]:
my_ops=[hello, const_scalar, const_matrix, mat_fill, mat_zeros, mat_ones, mat_randn, mat_randu]
for op in my_ops:
    res = op.numpy()
    print(type(res))
    print('\n')
    print(res)
    print('\n')

<class 'bytes'>


b'Hello World!'


<class 'numpy.int32'>


7


<class 'numpy.ndarray'>


[[1 2]
 [3 4]]


<class 'numpy.ndarray'>


[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


<class 'numpy.ndarray'>


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<class 'numpy.ndarray'>


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<class 'numpy.ndarray'>


[[-1.0635753   2.16728     0.65871626]
 [-1.1424781   1.4103571  -0.7665505 ]
 [-0.59387016 -1.3400667  -0.63527215]]


<class 'numpy.ndarray'>


[[0.84432447 0.46790934 0.7476342  0.5494753 ]
 [0.9748596  0.08018839 0.43241918 0.24025524]
 [0.52954996 0.86130905 0.5300566  0.9774357 ]
 [0.5692916  0.8774817  0.63553107 0.56248176]]




#### 1.3. Math operations:

In [6]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1* n2
print(n3.numpy())

2


In [7]:
n1 = tf.constant(4)
n2 = tf.constant(5)
n3 = tf.add(n1,n2)
print(n3.numpy())


9


In [8]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.multiply(n1,n2)
print(n3.numpy())

6


In [9]:
n1 = tf.constant(2)
n2 = tf.constant(3)
n3 = tf.pow(n1,n2)
print(n3.numpy())

8


#### 1.4. Matrix functions and operations:

In [10]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[1], [2]])
m3 = tf.matmul(m1, m2)                            # Matrix multiplication. Different from the element-wise multiplication with multiply().
print(m3.numpy())

[[ 5]
 [11]]


In [11]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[5, 6], [7, 8]])
m3 = tf.matmul(m1, m2)
print(m3.numpy())

[[19 22]
 [43 50]]


In [12]:
m3 = tf.multiply(m1, m2)
print(m3.numpy())

[[ 5 12]
 [21 32]]


In [13]:
m3 = m1*m2
print(m3.numpy())

[[ 5 12]
 [21 32]]


In [14]:
m3 = m1 + m2
print(m3.numpy())

[[ 6  8]
 [10 12]]


In [15]:
m3 = m1-m2
print(m3.numpy())

[[-4 -4]
 [-4 -4]]


In [16]:
m3 = m1 / m2
print(m3.numpy())

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
# Matrix functions.
m = tf.constant([[1.0,2.0],[3.0,4.0]])
m_diagonal = tf.linalg.diag([1,2,3])
m_transpose = tf.linalg.matrix_transpose(m)
m_inverse = tf.linalg.inv(m)
m_multiplied = tf.linalg.matmul(m, m_inverse)
m_determinant = tf.linalg.det(m)
my_matrices = [m, m_diagonal, m_transpose, m_inverse, m_multiplied, m_determinant]

for op in my_matrices:
     res = op.numpy()
     print(res)
     print('\n')

[[1. 2.]
 [3. 4.]]


[[1 0 0]
 [0 2 0]
 [0 0 3]]


[[1. 3.]
 [2. 4.]]


[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


[[ 1.0000000e+00  0.0000000e+00]
 [-4.7683716e-07  1.0000002e+00]]


-2.0




#### 1.5. TensorFlow Variable:

In [18]:
# Initializing Variables #1
x = tf.Variable(initial_value=5, name='x')       # Define.
y = tf.Variable(initial_value=6, name='y')       # Define.
f = (x - y)*y + 3                                # Define.

res=f.numpy()
print(res)

-3


In [19]:
# Initializing Variables #2
x = tf.Variable(initial_value=3, name='x')       # Define.
y = tf.Variable(initial_value=2, name='y')       # Define.
f = x*y + y + 3                                  # Define.

tf.print(f)

11


In [20]:
# Initializing Variables #3
x = tf.Variable(initial_value=7, name='x')       # Define.
y = tf.Variable(initial_value=3, name='y')       # Define.
f = x*y*y - y - 1                                # Define.
#init = tf.global_variables_initializer()        # Prepare: no more need in TF2.

tf.print(f)


59


In [21]:
my_tensor = tf.random.uniform((4,4),0,1)
my_var = tf.Variable(initial_value = my_tensor)                  # Initial value from a tensor.
#my_matrix = np.random.uniform(0,1,(4,4))
#my_var = tf.Variable(initial_value = my_matrix)                  # Initial value from a Numpy array.

tf.print(my_var)

[[0.403176785 0.265645146 0.697494149 0.549359322]
 [0.530969858 0.946849108 0.327228546 0.993217826]
 [0.977981806 0.0971862078 0.0358718634 0.560988784]
 [0.641904354 0.286241055 0.212258577 0.122191191]]


#### 1.6. TensorFlow Placeholder

In [22]:
#This was for TensorFlow 1.0
# a = tf.placeholder(tf.float32)
# b = tf.placeholder(tf.float32)
# y = tf.multiply(a, b)
# with tf.Session() as sess:
#     res = sess.run(y, feed_dict={a:2, b:3})           # Feed the actual valules.
#     print(res)

#tf.placeholder is not support in TF2. Adapted version:

# Define the function
@tf.function
def multiply(a, b):
    return tf.multiply(a, b)
    
#Here just creating constant normal TensorFlow variables.
a = tf.Variable(2.0)
b = tf.Variable(3.0)

# Call the function
res = multiply(a, b)

# Print the result
print(res.numpy())

6.0


In [24]:
#import pandas as pd

# Simulated data as NumPy array.
np.random.seed(123)
X1 = np.random.uniform(0.0, 1.0, (3,3))
X2 = np.random.normal(0.0, 1.0, (10,3))
b0 = np.array([1,2,3]).reshape((-1,1))
#
# The data may be a DataFrame.
#X1 = pd.DataFrame(X1)
#X2 = pd.DataFrame(X2)

# Use the same tensors directly
print(tf.matmul(X1, b0).numpy())  
print("\n")
print(tf.matmul(X2, b0).numpy())  

[[1.94930222]
 [3.25957209]
 [3.79321938]]


[[-5.18955106]
 [-0.47591604]
 [ 0.76363633]
 [ 4.6815933 ]
 [ 6.40295478]
 [-5.68629353]
 [-4.96309257]
 [-8.80927207]
 [-5.30648289]
 [ 3.05404772]]
